// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_l0Kj4NRCYhlCZsFzvsLUkRaLXGO64tk',
    appId: '1:617621721172:web:6abe544b7dd2ae894e5dc1',
    messagingSenderId: '617621721172',
    projectId: 'modul-3-fee6d',
    authDomain: 'modul-3-fee6d.firebaseapp.com',
    storageBucket: 'modul-3-fee6d.appspot.com',
    measurementId: 'G-0Z2FYXVKNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUWt-3twkExv1sr5AllUrBJy7JqIeaKA',
    appId: '1:617621721172:android:297cb53daa99ea484e5dc1',
    messagingSenderId: '617621721172',
    projectId: 'modul-3-fee6d',
    storageBucket: 'modul-3-fee6d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSU0NTc1ILweU1gfIvIZnMkpEHI7oMkA',
    appId: '1:617621721172:ios:aa4460446b83870e4e5dc1',
    messagingSenderId: '617621721172',
    projectId: 'modul-3-fee6d',
    storageBucket: 'modul-3-fee6d.appspot.com',
    iosBundleId: 'dompetdhuafaconceptmodul4.dompetdhuafaconceptmodul4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSU0NTc1ILweU1gfIvIZnMkpEHI7oMkA',
    appId: '1:617621721172:ios:aa4460446b83870e4e5dc1',
    messagingSenderId: '617621721172',
    projectId: 'modul-3-fee6d',
    storageBucket: 'modul-3-fee6d.appspot.com',
    iosBundleId: 'dompetdhuafaconceptmodul4.dompetdhuafaconceptmodul4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_l0Kj4NRCYhlCZsFzvsLUkRaLXGO64tk',
    appId: '1:617621721172:web:81cc7169b463cf2f4e5dc1',
    messagingSenderId: '617621721172',
    projectId: 'modul-3-fee6d',
    authDomain: 'modul-3-fee6d.firebaseapp.com',
    storageBucket: 'modul-3-fee6d.appspot.com',
    measurementId: 'G-ZPDBHBKKYM',
  );

}